### ISSUE TITLE
InvalidProgramException from short test program

### ISSUE THREAD

**Issue by WalkerCodeRanger** [oleg-st/InlineMethod.Fody#14]
Using `InlineMethod.Fody` 0.8.2 and `Fody` 6.9.1 the following test code outputs invalid IL for the `Caller` method and throws `InvalidProgramException` when it is called with `Inline.Caller([2, 1]);`.

This code is derived from an actual program that produced the error. I tried to simplify as much as possible, but it seems both the `foreach` and `switch` are necessary to get the error.

```csharp
internal static class Inline
{
    public static void Caller(IEnumerable<int> values)
    {
        foreach (var value in values)
        {
            var x = value switch
            {
                1 => 3,
                2 => 4,
                _ => throw new NotSupportedException(),
            };
            _ = Called(x);
        }
    }

    [Inline]
    private static int Called(int v)
        => v;
}
```

**Comment by oleg-st** [comment]
Instructions from finally block is removed as unreachable, fixed in 8bdae8a808594e07f98e148e2fc4f63016a313ae

**Comment by oleg-st** [comment]
Released in 0.8.3

**Comment by WalkerCodeRanger** [comment]
Upgrading to 0.8.3 does cause my test program for this issue to pass. I'm getting other invalid program issues still (I assumed that all the issues were because of this, but there must have been others). I'll file separate bug(s) for those.
