### ISSUE TITLE
BUG: InvalidProgramException from method calling inlined method and containing a `using` statement

### ISSUE THREAD

**Issue by WalkerCodeRanger** [oleg-st/InlineMethod.Fody#15]
Using v0.8.3, Fody v6.9.1, and .NET 9, the following program throws `System.InvalidProgramException: Common Language Runtime detected an invalid program.`. Note, for some reason, the exception happens when it is compiled for Debug but not when compiled for Release.

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        Callee();
        while (true)
        {
            using var output = Console.OpenStandardOutput();
            break;
        }
    }

    [Inline]
    private static void Callee()
        => Console.WriteLine("Hello, World!");
}
```

**Comment by oleg-st** [comment]
Fixed in 0..8.4

**Comment by WalkerCodeRanger** [comment]
Yes, v0.8.4 does fix this test case. ~~I'm still getting `InvalidProgramException` when I try to inline certain methods in my real codebase. I'll try to derive a test case for that soon and file another bug.~~
