### ISSUE TITLE
BUG: Another `InvalidProgramException`

### ISSUE THREAD

**Issue by WalkerCodeRanger** [oleg-st/InlineMethod.Fody#16]
Using v0.8.4 and Fody v6.9.1 on .NET 9.

The test program below throws an `InvalidProgramException`. It seems to have something to do with returning the result of calling the setter when assigning a value from a field. For example, splitting the `return` out to its own line or doing `return s.Value = default` will eliminate the exception.

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        Caller();
    }

    private static Struct Caller()
    {
        Struct s = default;
        return s.Value = Struct.Default;
    }

    private readonly struct Struct
    {
        public static readonly Struct Default = default;

        public Struct Value
        {
            [Inline]
            set { }
        }
    }
}
```

P.S. Thanks for the fairly quick fixes to these `InvalidProgramException` bugs and the `InlineParameter` attribute

**Comment by oleg-st** [comment]
I think it's fixed in 0.8.5

**Comment by WalkerCodeRanger** [comment]
v0.8.5 does fix that exact code. However, when trying it in my actual program I still got `InvalidProgramException` from trying to inline the same setter as I was before. So, it seems like v0.8.5 didn't fully fix the issue. Here is a slightly modified version of the code that still throws `InvalidProgramException` and is in some ways closer to my actual code.

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        Caller();
    }

    private static void Caller()
    {
        Struct s = default;
        _ = s.Value = Struct.None;
    }

    private readonly struct Struct
    {
        public static readonly Struct None = default;
        private readonly int offset = 0;

        private readonly List<Struct> values = [None];

        public Struct() { }

        public Struct Value
        {
            [Inline]
            set => values[offset] = value;
        }
    }
}
```

**Comment by oleg-st** [comment]
Fixed in 0.8.6

**Comment by WalkerCodeRanger** [comment]
I'm still having problems with v0.8.6. It seems like the issues are sensitive to very minor things as if a general algorithm for handling all cases is missing. Here is a program that throws `InvalidProgramException` in v0.8.6. Notice that it is almost identical to the previous one, with just the variable `value` extracted.

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        Caller();
    }

    private static void Caller()
    {
        Struct s = default;
        var value = Struct.None;
        _ = s.Value = value;
    }

    private readonly struct Struct
    {
        public static readonly Struct None = default;
        public readonly int offset = 0;

        public readonly List<Struct> values = [None];

        public Struct() { }

        public Struct Value
        {
            [Inline]
            set => values[offset] = value;
        }
    }
}
```

**Comment by oleg-st** [comment]
Fixed in 0.8.7

**Comment by WalkerCodeRanger** [comment]
Thanks, with v0.8.7 I am now able to inline the setter I was trying to inline.
